# k8s/overlays/testing/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization
resources:
  - ../../base
configMapGenerator:
  - name: app-dynamic-config
    literals:
      - database_name=test_db
      - database_owner=test_user
secretGenerator:
  - name: pg-app-secret
    literals:
      - username=test_user
      - password=test_password_123
