# k8s/overlays/testing/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - ../../base
secretGenerator:
  - name: pg-root
    namespace: postgres
    literals:
      - username=postgres
      - password=super-safe-root-password-123
  - name: pg-user
    namespace: postgres
    literals:
      - username=blog-db
      - password=blog_password_123

patches:
  - path: patch-testing.yaml
