# k8s/overlays/testing/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - ../../base
  - dummy-secrets.yaml

patches:
  - path: patch-nginx.yaml # that form in case of patching entire yaml file
  - target:                # the other form for patching selected key words
      kind: Cluster
      name: postgresql
      namespace: postgres
    path: patch-postgres.yaml
    