apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgres
spec:
  instances: 1
  storage: 1Gi    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  namespace: postgres
spec:
  # Na testy w GitHub Actions 1 replika podu PHP/Nginx zazwyczaj w zupełności wystarczy
  replicas: 1           


