apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  namespace: postgres
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx-deplo
        image: ghcr.io/1xxxxxxx4/blog-kubernetes-nginx-dev:latest
      - name: php-deplo
        image: ghcr.io/1xxxxxxx4/blog-kubernetes-php-dev:latest
        