events {
}
http {
   include /etc/nginx/mime.types;
   charset utf-8;
   default_type application/octet-stream;

   access_log /dev/stdout;
   error_log /dev/stderr;

   server {
       listen 80;
       server_name localhost;
       root /usr/share/nginx/html;
       index index.php;

       location / {
           try_files $uri $uri/ /index.php?$query_string;
           }

           location ~ /\. {
               deny all;
               access_log off;
               log_not_found off;
	

            location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;
            }
            location ~* \.(jpg|jpeg|png|mp4)$ {
              deny all;
              access_log off;
              log_not_found off;
            }
          
          }
    } 
}
   
