# k8s/overlays/prod/configMap-managment
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-db-config
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: app-dynamic-config
    kind: configMap
  data:
    - secretKey: database_name
      remoteRef:
        key: prod/postgres
        property: config
        jsonPkg: db_name

    - secretKey: database_owner
      remoteRef: 
        key: prod/postgres
        property: config
        jsonPkg: db_owner