# k8s/overlays/production/secrets-managment.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-db-secrets
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: secretStore
  target:
    name: pg-app-secret
    creationPolicy: Owner
  data: 
    - secretKey: username
      remoteRef: { key: prod/postgres, property: user }
    - secretKey: password
      remoteRef: { key: prod/postgres, property: password }
    - secretKey: database
      remoteRef: { key: prod/postgres, property: db_name }
      