# k8s/overlays/production/secrets-managment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault-auth-sa
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth: 
        kubernetes:
          mountPath: "kubernetes"
          role: "postgres-app-role"
          serviceAccountRef:
            name: "eso-vault-auth-sa"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-db-secrets
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: pg-app-secret
    creationPolicy: Owner
  data: 
    - secretKey: username
      remoteRef: 
        key: prod/postgres
        property: config
        jsonPkg: user

    - secretKey: password
      remoteRef: 
        key: prod/postgres
        property: config
        jsonPkg: password

    - secretKey: database
      remoteRef:
        key: prod/postgres
        property: config
        jsonPkg: db_name