apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-www-php
  template:
    metadata:
      labels:
        app: server-www-php
    spec:
      imagePullSecrets:
        - name: ghcr-secret 
      containers:
      - name: nginx-deplo
        image: ghcr.io/1xxxxxxx4/blog-kubernetes-nginx:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80

      - name: php-deplo
        image: ghcr.io/1xxxxxxx4/blog-kubernetes-php:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: DB_PORT
        volumeMounts:
        - name: db-secret-volume
          mountPath: "/magic-variables/secrets"
          readOnly: true
        volumes:
        - name: db-secret-volume
          secret: 
            secretName: user-secret
            items:
            - key: username
              path: db-user
            - key: password
              path: db-pass
