apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgres
  annotations:
    # sync-wave = plugin ordering implementation to kubernetes cluster
    argocd.argoproj.io/sync-wave: "0"

spec:
  description: "Postgresdb"
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  imagePullPolicy: IfNotPresent
  instances: 3
  
  superuserSecret:
    name: pg-root
  bootstrap:
    initdb:
      database: blog-db
      secret:
        name: pg-user
      configMapRefs:
        key: postInitSQLmap.sql
        name: pg-cfg

  storage: 
    storageClass: longhorn
    size: 2Gi 
