name: Testing dev branch

on:
  workflows: ["1.Build and Push Docker images branch dev"]
    types: 
      - completed
      
    env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PHP: ghcr.io/1xxxxxxx4/blog-kubernetes-php-dev
  IMAGE_NAME_NGINX: ghcr.io/1xxxxxxx4/blog-kubernetes-nginx-dev

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      # 1. Download code from repo, branch dev
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: 
          ref: 'dev'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '1'

      # 2. Loggingg into GHCR
      # GITHUB delivers GITHUB_TOKEN automaticaly
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Creating KIND cluster
      - name: create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind-dev-cluster

      # 4. Install cnpg.io on my cluster
      - name: install postgresql 
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm repo update
          helm upgrade --install cnpg cnpg/cloudnative-pg \
            --namespace cnpg-system \
            --create-namespace
      
      # 5. Wait for CNPG operator to get ready
      - name: Wait for CNPG operator 
        run : |
          kubectl wait --namespace cnpg-system \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/name=cloudnative-pg \
            --timeout=120s

      # 6. applying resources into cluster
      - name: applying resources with kustomize
        run: |
          kubectl apply -k ./k8s/overlays/testing
      
      
          
