name: Build and Push Docker images

on:
  push:
    branches:
      - main # pipeline uruchomi sie przy kazdym pushu do galezi main
      - adding-php-code

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PHP: ghcr.io/1xxxxxxx4/blog-kubernetes-php
  IMAGE_NAME_NGINX: ghcr.io/1xxxxxxx4/blog-kubernetes-nginx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      # 1. Downloading code from repo to bulding machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Loggingg into GHCR
      # GITHUB delivers GITHUB_TOKEN automaticaly
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # 3. Building and pushing php image
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/php/Dockerfile.php
          push: true
          tags: |
            ${{ env.IMAGE_NAME_PHP }}:latest
            ${{ env.IMAGE_NAME_PHP }}:${{ github.sha }}

      # 4. Building nginx
      - name: Bulding and pushing nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/nginx/Dockerfile.nginx
          push: true
          tags: |
            ${{ env.IMAGE_NAME_NGINX }}:latest
            ${{ env.IMAGE_NAME_NGINX }}:${{ github.sha }}
          cache-from: ""
          cache-to: ""
          
      # 5.a Test deploy     
      - name: Create KIND cluster
        uses: helm/kind-action@v1.12.0
      # 5.b
      - name: Install CloudNativePG operator
        run: |
          kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.23.0.yaml
          echo "Czekam na uruchomienie operatora CNPG..."
          kubectl wait --namespace cnpg-system --for=condition=ready pod -l app.kubernetes.io/name=cloudnative-pg --timeout=120s
      # 5.c
      - name: Create Postgres namespace
        run: |
          kubectl create namespace postgres --dry-run=client -o yaml | kubectl apply -f -
      # 5.d
      - name: Test deploy manifests via kustomize
        run: |
          kubectl apply -k k8s/overlays/testing
      # 5.e
      - name: Verify test deployment
        run: |
          echo "=== Sprawdzam utwrzone zasoby w namespace postgres ==="
          kubectl get all -n postgres
          kubectl get secrets -n postgres
          kubectl get configmaps -n postgres